export const DELETE_ALLPRODUCTS_REQUEST = 'DELETE_ALLPRODUCTS_REQUEST'
export const DELETE_ALLPRODUCTS_SUCCESS = 'DELETE_ALLPRODUCTS_SUCCESS'
export const DELETE_ALLPRODUCTS_RESET = 'DELETE_ALLPRODUCTS_RESET'
export const DELETE_ALLPRODUCTS_FAIL = 'DELETE_ALLPRODUCTS_FAIL'

export const SCRAPEPRODUCT_REQUEST = 'SCRAPEPRODUCT_REQUEST'
export const SCRAPEPRODUCT_SUCCESS = 'SCRAPEPRODUCT_SUCCESS'
export const SCRAPEPRODUCT_RESET = 'SCRAPEPRODUCT_RESET'
export const SCRAPEPRODUCT_FAIL = 'SCRAPEPRODUCT_FAIL'

export const ALL_PRODUCS_REQUEST = 'ALL_PRODUCS_REQUEST'
export const ALL_PRODUCS_SUCCESS = 'ALL_PRODUCS_SUCCESS'
export const ALL_PRODUCS_FAIL = 'ALL_PRODUCS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'